// DcuKernelInitStubs — empty stubs for all init*Kernels*() functions
//
// In the NVIDIA CUDA build, these functions are auto-generated by nvcc from
// the .cu kernel files and are called by createPxg*() to force static linkage
// of the GPU kernel modules.
//
// On DCU, kernels are loaded dynamically via hipModuleLoad() and resolved at
// runtime by the KernelWrangler.  The init*Kernels*() registration is not
// needed — but the host-side .cpp files still call them from createPxg*().
// We provide empty stubs so the host-side code compiles and links unchanged.

// Common
extern "C" void initCommonKernels0() {}
extern "C" void initCommonKernels1() {}
extern "C" void initCommonKernels2() {}

// Broadphase
extern "C" void initBroadphaseKernels0() {}
extern "C" void initBroadphaseKernels1() {}

// Narrowphase
extern "C" void initNarrowphaseKernels0() {}
extern "C" void initNarrowphaseKernels1() {}
extern "C" void initNarrowphaseKernels2() {}
extern "C" void initNarrowphaseKernels3() {}
extern "C" void initNarrowphaseKernels4() {}
extern "C" void initNarrowphaseKernels5() {}
extern "C" void initNarrowphaseKernels6() {}
extern "C" void initNarrowphaseKernels7() {}
extern "C" void initNarrowphaseKernels8() {}
extern "C" void initNarrowphaseKernels9() {}
extern "C" void initNarrowphaseKernels10() {}
extern "C" void initNarrowphaseKernels11() {}

// Solver
extern "C" void initSolverKernels0() {}
extern "C" void initSolverKernels1() {}
extern "C" void initSolverKernels2() {}
extern "C" void initSolverKernels3() {}
extern "C" void initSolverKernels4() {}
extern "C" void initSolverKernels5() {}
extern "C" void initSolverKernels6() {}
extern "C" void initSolverKernels7() {}
extern "C" void initSolverKernels9() {}
extern "C" void initSolverKernels10() {}
extern "C" void initSolverKernels11() {}
extern "C" void initSolverKernels13() {}

// SimulationController
extern "C" void initSimulationControllerKernels0() {}
extern "C" void initSimulationControllerKernels1() {}
extern "C" void initSimulationControllerKernels2() {}

// Articulation
extern "C" void initArticulationKernels1() {}
extern "C" void initArticulationKernels2() {}
extern "C" void initArticulationKernels3() {}
extern "C" void initArticulationKernels4() {}

// SoftBody
extern "C" void initSoftBodyKernels0() {}
extern "C" void initSoftBodyKernels1() {}

// FEM Cloth
extern "C" void initFEMClothKernels0() {}
extern "C" void initFEMClothKernels1() {}
extern "C" void initFEMClothKernels2() {}

// Particle System
extern "C" void initParticleSystemKernels0() {}
extern "C" void initDiffuseParticlesKernels0() {}

// Isosurface / SparseGrid / Anisotropy / Algorithms / SDF
extern "C" void initIsosurfaceExtractionKernels0() {}
extern "C" void initSparseGridStandaloneKernels0() {}
extern "C" void initAnisotropyKernels0() {}
extern "C" void initAlgorithmsKernels0() {}
extern "C" void initSdfConstructionKernels0() {}
